### ISSUE TITLE
Bio::Tools:EUtilities Looks like a typo

### ISSUE THREAD

**Issue by wgallin** [bioperl/Bio-EUtilities#13]
I'm trying to use Bio::Tools::EUtilities and I am getting an error:

Can't locate object method "warn" via package "self" (perhaps you forgot to load "self"?) at /usr/local/share/perl/5.26.1/Bio/Tools/EUtilities.pm line 152.

I have th latest version installed:
sudo cpanm Bio::Tools::EUtilities.pm
Bio::Tools::EUtilities is up to date. (1.76)

The problem at line 152 seems to be that there is a missing character, line 152 reads:

self->warn("NCBI $eutil error: " . $simple->{ERROR});

I think it should likely read:

$self->warn("NCBI $eutil error: " . $simple->{ERROR});

I haven't figured out how to edit this file: is there a chance of getting an update that corrects this, if indeed this is a problem?

Thanks

**Comment by majensen** [comment]
Doh! Nice catch @wgallin

**Comment by carandraug** [comment]
Fixed with 943e355 . Closing. Thank you for the report and fix.
