### ISSUE TITLE
incorrect dependency

### ISSUE THREAD

**Issue by chorny** [bioperl/Bio-EUtilities#3]
depends on inc::TestHelper which is not available on CPAN

**Comment by wang-q** [comment]
I encounter the same problem when add CJFIELDS/Bio-EUtilities-1.73.tar.gz to [Stratopan](https://stratopan.com/), CJFIELDS/Bio-EUtilities-1.72.tar.gz is OK.

I guess that [AutoPrereqs] plugin of Dist::Zilla causes this problem. 1.72 uses plugin bundle [@CJFIELDS] while 1.73 uses [@BioPerl].

**Comment by cjfields** [comment]
Strange, for whatever reason I haven't been receiving emails for issues with this distribution   Will try to have a look into this, only about three years along...

**Comment by cjfields** [comment]
This seems to be addressed now in the latest release.  The `[AutoPrereqs]` dependency wasn't skipping in the 1.73 release.  The 1.74 release had it set but it didn't skip as set, so I reran and debugged the `META.json` output until I found a pattern that worked.
