### ISSUE TITLE
Difference between protein_pubmed_refseq, protein_pubmed, and protein_pubmed_weighted?

### ISSUE THREAD

**Issue by strixeh** [bioperl/Bio-EUtilities#5]
Hey, 

I would like to ask what the difference is between protein_pubmed_refseq, protein_pubmed, and protein_pubmed_weighted?

Best,
Nils

**Comment by cjfields** [comment]
@strixeh these are not really values from this distribution but are [specific elink names](https://eutils.ncbi.nlm.nih.gov/entrez/query/static/entrezlinks.html).  Not sure if this is relevant for an issue
