### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by katbeaulieu** [bioperl/Bio-EUtilities#8]
Hi there,
Could someone point me in the direction of the requirements of this interface? What version of perl does it require, what are any other dependencies?
Cheers!
Katherine

**Comment by carandraug** [comment]
They are listed on the `Makefile.PL` of the release.  The released tarballs also have `META.json` and `META.yml` with that information.

**Comment by katbeaulieu** [comment]
Thanks for the quick reply!

**Comment by katbeaulieu** [comment]
I've just done a 'find' on the source code for release 1.75 and there was no file 'Makefile.pl', 'META.json', or 'META.yaml'. Am I looking in the wrong place?

**Comment by carandraug** [comment]
On 24 April 2017 at 13:00, katbeaulieu <notifications@github.com> wrote:
>
> I've just done a 'find' on the source code for release 1.75 and there was no file 'Makefile.pl', 'META.json', or 'META.yaml'. Am I looking in the wrong place?
>

Probably. Where are you looking?

**Comment by carandraug** [comment]
I just realised you are probably using github "releases".  Do not use those, github generates them automatically from git tags so what you get is a checkout of the repository.  The releases are prepared with distzilla. Please get your releases from cpan.

I will remove the github non-sense releases.
