### ISSUE TITLE
api_key support

### ISSUE THREAD

**Issue by pcantalupo** [bioperl/Bio-EUtilities#9]
Does this repo support the new [api_key parameter](https://ncbiinsights.ncbi.nlm.nih.gov/2017/11/02/new-api-keys-for-the-e-utilities/)?

**Comment by donutbrew** [comment]
@pcantalupo I added this to my fork for now https://github.com/donutbrew/Bio-EUtilities. 
@cjfields if you want, I can contribute, but I'm not sure of the etiquette here.

**Comment by kiwiroy** [comment]
@donutbrew LGTM could you make a pull request as it would be good to have this functionality.

**Comment by cjfields** [comment]
@donutbrew as @kiwiroy mentioned, a pull request would be awesome!

**Comment by donutbrew** [comment]
Right on. https://github.com/bioperl/Bio-EUtilities/pull/10

**Comment by cjfields** [comment]
Merged in, thanks!  I'll push out a quick point release with this in.
